// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQhjItoos51timoHbGYiTH-hMHGDjrEl8',
    appId: '1:798994760295:web:1693fcbaa89f8402ca4ac2',
    messagingSenderId: '798994760295',
    projectId: 'flutter-app-f1f05',
    authDomain: 'flutter-app-f1f05.firebaseapp.com',
    storageBucket: 'flutter-app-f1f05.appspot.com',
    measurementId: 'G-4YNZ3EBDE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM8eYIWo_QJ2cMEKSa7Oe6RYJcfo2_EDk',
    appId: '1:798994760295:android:fa140fcbfb24b073ca4ac2',
    messagingSenderId: '798994760295',
    projectId: 'flutter-app-f1f05',
    storageBucket: 'flutter-app-f1f05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf0V4RLK8oGN2PeAT_bSDbGyfTUJLH9fM',
    appId: '1:798994760295:ios:8b83cfb46266f71bca4ac2',
    messagingSenderId: '798994760295',
    projectId: 'flutter-app-f1f05',
    storageBucket: 'flutter-app-f1f05.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf0V4RLK8oGN2PeAT_bSDbGyfTUJLH9fM',
    appId: '1:798994760295:ios:8b83cfb46266f71bca4ac2',
    messagingSenderId: '798994760295',
    projectId: 'flutter-app-f1f05',
    storageBucket: 'flutter-app-f1f05.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQhjItoos51timoHbGYiTH-hMHGDjrEl8',
    appId: '1:798994760295:web:61755a794a718658ca4ac2',
    messagingSenderId: '798994760295',
    projectId: 'flutter-app-f1f05',
    authDomain: 'flutter-app-f1f05.firebaseapp.com',
    storageBucket: 'flutter-app-f1f05.appspot.com',
    measurementId: 'G-07QD5XX794',
  );

}